sudo: false
cache:
  - pip
  - directories:
    - $HOME/.cache/pip
language: python
python:
  - "2.7"
  - "3.4"
  - "3.5"
  - "3.6"
  - "3.7"
install:
  - ./manage.sh update_dev_packages
script:
  - ./manage.sh pep8_check
  - ./manage.sh unit_tests
  - ./manage.sh py_test_coverage
